function patch_img = ref2srgbpatches( ...
    ref,...
    cmf, illum,...
    patch_w, patch_h,...
    sep_size,...
    columns,...
    wp )

if nargin < 8
    % Perfect as white point
    wp = color_tool.ref2xyz( ones(1,size(ref,2)), cmf, illum );
end

xyz_patch = color_tool.ref2xyzpatches( ...
    ref,...
    cmf, illum,...
    patch_w, patch_h,...
    sep_size,...
    columns );

patch_img = color_tool.xyz2srgb( xyz_patch, wp );

end