% Read the inkjet printed cellular Neugebauer information
function [ret_dc, ret_spec] = read_inkjet_cellular( ...
    fname_dc, ...
    fname_spec, ...
    fmin_lambda,...
    finterval,...
    fmax_lambda,...
    omin_lambda, ...
    ointerval,...
    omax_lambda )

    if nargin < 1
        [filename, pathname] = uigetfile( '*.txt', 'DC value for samples' );
        fname_dc = strcat(pathname,filename);
        [filename, pathname] = uigetfile( '*.txt', 'Spectrum value for samples' );
        fname_spec = strcat(pathname,filename);
    end
    
    % digital counts need not 
    ret_dc = dlmread( fname_dc );

    spec_unlim = dlmread( fname_spec );
    
    % spectrum need to be truncate because, well, I don't know the reason 
    % either, the dlmread always read one more column with zeros
    spec_unlim = spec_unlim(:,1:end-1);
    
    ret_spec = color_tool.ref2ref(...
        spec_unlim, ...
        fmin_lambda, finterval, fmax_lambda,...
        omin_lambda, ointerval, omax_lambda );

end
